# This action tests the "download-artifacts" action. Note that it runs on workflow_run events, so changes must
# be checked into the main branch before they can be tested.

name: 'test-download-artifacts'

on:
  workflow_run:
    workflows: ["create-artifacts"]
    types:
      - completed

jobs:
  test-download-artifacts:
    runs-on: ubuntu-latest
    name: test download-artifacts
    steps:
      - uses: actions/checkout@v2
      - name: Download and extract artifacts
        uses: ./download-artifacts
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          pattern: '^.*\.download$'
          extract: true
      - name: Test that "test.download" got downloaded
        run: |
          [[ -f artifacts/test.download.zip ]]
          cat artifacts/test.download/test-file.download
      - name: Test that "test.not-download" did not get downloaded
        run: |
          [[ ! -f artifacts/test.not-download.zip ]]
          [[ ! -f artifacts/test.not-download/test-file.not-download ]]


  test-get-artifacts-single:
    runs-on: ubuntu-latest
    name: test get-artifacts single job
    steps:
      - uses: actions/checkout@v2
      - name: Download and extract single run's artifacts.
        uses: ./download-artifacts
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow_run_id: ${{ github.event.workflow_run.id }}
          artifacts: test-file.download
          target_dir: /tmp/downloads/
          unzip: true
      - name: Test that "test.download" got downloaded
        run: |
          [[ -f  /tmp/downloads/${{ github.event.workflow_run.id }}/test-file.download ]]
      - name: Test that "test.not-download" did not get downloaded
        run: |
          [[ ! -f  /tmp/downloads/${{ github.event.workflow_run.id }}/test-file.not-download ]]

  test-get-artifacts-multiple:
    runs-on: ubuntu-latest
    name: test get-artifacts-multiple
    steps:
      - uses: actions/checkout@v2
      - name: Download and extract single run's artifacts.
        uses: ./download-artifacts
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: create-artifacts.yml
          artifacts: test-file.download test-file.not-download
          branch: main
          target_dir: /tmp/downloads/
          unzip: true
      - name: Test that "test.download" got downloaded
        run: |
          [[ -f /tmp/downloads/${{ github.event.workflow_run.id }}/test-file.download ]]
          [[ -f /tmp/downloads/${{ github.event.workflow_run.id }}/test-file.not-download ]]
          [[ ( ls -l /tmp/downloads/ | wc -l ) -gt 1 ]]
